### ISSUE TITLE
[Meta] Schema extensions

### ISSUE THREAD

**Issue by marktani** [graphcool/content#210]
* [x] Simple
  * [x] Overview
  * [x] Introduction
    * [x] Making Requests
  * [x] Mutations
    * [x] overview
    * [x] Types
      * [x] cud
    * [x] Relations
      * [x] multiplicities
    * [x] Nested (overview)
    * [x] extensions
      * [x] authenticated
  * [x] Queries
    * [x] overview
    * [x] Types
      * [x] one/multiple
      * [x] aggregation
    * [x] Relations
      * [x] traverse to-one
      * [x] traverse to-many
      * [x] aggregation
    * [x] extensions
      * [x] authenticated user
    * [x] query arguments
  * [x] Subscriptions
    * [x] overview
    * [x] Types
      * [x] cud
      * [x] combine
    * [x] Relations
      * [x] feature request
    * [x] filters
  * [x] Error Handling
* [x] Schema
  * [x] generated queries/mutations
    * [x] types
    * [x] relations
* [x] Functions
  * [x] Overview
  * [x] extensions
    * [x] payload/extend
  * [x] SDK
  * [x] runtime
  * [x] use cases
    * [ ] RP
    * [ ] SSS
    * [x] SE
* [x] Integrations
* [x] Relay
  * [x] Overview
  * [x] Making Requests
  * [x] Mutations
    * [x] overview
    * [x] Types
      * [x] cud
    * [x] Relations
      * [x] multiplicities
    * [x] Nested (overview)
    * [x] authenticated
  * [x] Queries
    * [x] overview
    * [x] Types
      * [x] one/multiple
      * [x] aggregation
    * [x] Relations
      * [x] traverse to-one
      * [x] traverse to-many
      * [x] aggregation
    * [x] query arguments
    * [x] authenticated user
  * [x] Error Handling
---
* [ ] General
  * [x] frontmatter
    * [x] simple-relay-twin
  * [x] alias linking `[]()`
  * [ ] homepage sidenav
