### ISSUE TITLE
[Meta] new content

### ISSUE THREAD

**Issue by marktani** [graphcool/content#86]
* [x] cli chapter
  * [x] iterate based on feedback
  * [x] project collaboration/manage different stages (git...) @nikolasburk 
  * [x] `graphcool clone` section
  * [x] proof read when CLI API is stable
* [x] schema chapter
  * [x] Generated Operations Based On Types/Relations/Fields
  * [x] required relations
* [x] model -> type (note: previously called "model")
* [ ] migrations
  * [x] overview (update homepage)
  * [x] types
  * [x] fields
  * [x] relations
  * [ ] enums
* [ ] console
  * [x] project settings
  * [x] schema
  * [x] data
  * [x] permissions
  * [x] functions
  * [x] integrations
  * [ ] playground
    * [x] queries/mutations
    * [x] subscriptions
    * [x] history/tabs
    * [ ] docs
* [ ] functions chapter
  * [x] inline vs webhook url
    * [x] inline: runtime, promises, timeouts, ...
  * [x] request pipeline
    * [x] different hook points
    * [x] error handling
  * [x] SSS
* [x] auth/auth chapter
* [x] integrations
  * [x] email auth
  * [x] guest auth
  * [x] add new section "more integrations"
* [ ] overview for all categories
  * [x] schema
  * [x] functions
  * [x] migrations
  * [x] file handling
  * [x] authentication
  * [x] integrations
  * [x] CLI
  * [x] Console
  * [ ] API
* [ ] iterate above
* [x] cleanup
  * [x] remove platform chapter
  * [x] remove old articles in GC
---
* [x] clean up TODOs
* [x] frontmatters
* [x] link content in frontmatter
* [x] input correct aliases: `()`
* [ ] iterate titles
* [x] iterate descriptions
---

* [x] think about three starter guides

**Comment by marktani** [comment]
`[Enum!]!` migration and default value:

```
